config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'messages#index'
  
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if @message.save
      flash[:success] = 'Message が正常に投稿されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Message が投稿されませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      flash[:success] = 'Message は正常に更新されました'
      redirect_to @message
      
    else
      flash.now[:danger] = 'Message は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @message.destroy
    
    flash[:success] = 'Message は正常に削除されました'
    redirect_to messages_url
  end
  
  private
  def set_message
    @message = Message.find(params[:id])
  end
  
  # Strong Parameter
  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |f| %>
  <% if message.erros.any? %>
    <div id="error_explanation">
      <ul>
        <% message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :content, 'メッセージ' %>
  <%= f.text_field :content %>
  
  <%= f.submit '投稿' %>
<% end %>

app/views/messages/edit.html.erb
<h1>id: <%= @message.id %> のメッセージ編集ページ</h1>

<%= render 'form', message: @message %>

<%= link_to '一覧に戻る', messages_path %>

app/views/messages/index.html.erb
<h1>メッセージ一覧</h1>

<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.id, message %> : <%= message.content %></li>
  <% end %>
</ul>

<%= link_to '新規メッセージの投稿', new_message_path %>

app/views/messages/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= form_with(model: @message, local: true) do |f| %>
  <%= f.label :content, 'メッセージ' %>
  <%= f.text_field :content %>

  <%= f.submit '投稿' %>
<% end %>

<% link_to '一覧に戻る', messages_path %>

app/views/messages/show.html.erb
<h1>id: <%= @message.id %>のメッセージ詳細ページ</h1>

<p><%= @message.content %></p>

<%= link_to '一覧に戻る', messages_path %>
<%= link_to 'このメッセージを編集する', edit_message_path(@message) %>
<%= link_to 'このメッセージを削除する', @message, method: :delete, data: { confirm: '本当に削除してよろしいですか？'} %>